# Files
executable = /afs/cern.ch/user/a/almuhamm/private/CMSSW_12_4_8/src/L1NanoAOD/l1macros/condorsubmission/scriptcondor_performances_nano.sh
output = /afs/cern.ch/user/a/almuhamm/private/condorZMuMu/log/scriptcondor_$(Process).out
error = /afs/cern.ch/user/a/almuhamm/private/condorZMuMu/log/scriptcondor_$(Process).err
log = /afs/cern.ch/user/a/almuhamm/private/condorZMuMu/log/scriptcondor_$(Process).log
arguments    = $(Process)


transfer_input_files = $(filename)
arguments            = $(filename)  /afs/cern.ch/user/a/almuhamm/private/condorZMuMu/output_$(Process).root ZToMuMu

should_transfer_files = YES
transfer_input_files = scriptcondor_performances_nano.sh, /afs/cern.ch/user/a/almuhamm/private/CMSSW_12_4_8/src/L1NanoAOD/l1macros/performances_nano.py, /afs/cern.ch/user/a/almuhamm/private/CMSSW_12_4_8/src/L1NanoAOD/config_cards/full_ZToMuMu.yaml
when_to_transfer_output = ON_EXIT

# Resource requests
request_cpus   = 4
request_memory = 100MB
request_disk   = 100MB

# Run job
#queue filename matching files  /eos/cms/store/data/Run2023B/Muon0/NANOAOD/PromptNanoAODv11p9_v1-v2/*/*.root
queue filename matching files /eos/user/a/almuhamm/ZMu_Test/outNANOAOD/Run2023B/Muon0/NANOAOD/PromptNanoAODv11p9_v1-v2/*/*.root 
queue 100 
